name: Autobuild
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:   
      - run: echo "Create release for branch:${{ gitea.ref_name }} ref:${{ gitea.ref }} repo:${{ gitea.repository }}."
       
      - run: |
          echo "1.1.1.1" >> /etc/resolv.conf
          
      - run: |
          cat /etc/resolv.conf
      
      - name: Check out repository code
        uses: actions/checkout@v3
        token: ${{ secrets.TOKEN }}
        ref: ${{ gitea.ref_name }}

      #- uses: nelonoel/branch-name@v1
      #- uses: Actions/branch-name@v1
      # - name: Get branch-name repo
        # uses: https://github.com/nelonoel/branch-name@v1
        # with:
          # repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}   
        
      - name: Create build.zip
        uses: https://github.com/vimtor/action-zip@v1
        with:
          files: build/ 
          recursive: false
          dest: build.zip
      
      - name: Upload binaries to release
        uses: https://github.com/svenstaro/upload-release-action@v2
        with:
          file: build.zip
          asset_name: ${BRANCH_NAME}.zip
          tag: ${BRANCH_NAME}
          overwrite: true
      